### ISSUE TITLE
enum_hash.hpp hack is not working

### ISSUE THREAD

**Issue by jpcima** [rerrahkr/BambooTracker#165]
Hi, the std::hash template overload found under `GNUC` in `enum_hash.hpp` does not build.
It passes after removing it. The build errors are as follows:

- Using clang 9.0.0
```
In file included from ../BambooTracker/gui/effect_description.cpp:1:
In file included from ../BambooTracker/gui/effect_description.hpp:8:
../BambooTracker/enum_hash.hpp:8:10: error: redefinition of 'hash'
  struct hash {
         ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/bits/functional_hash.h:101:12: note: previous definition is here
    struct hash : __hash_enum<_Tp>
           ^
1 error generated.
```

- Using gcc 9.2.0

```
In file included from ../BambooTracker/gui/effect_description.hpp:8,
                 from ../BambooTracker/gui/effect_description.cpp:1:
../BambooTracker/enum_hash.hpp:8:10: error: redefinition of 'struct std::hash<_Tp>'
    8 |   struct hash {
      |          ^~~~
In file included from /usr/include/c++/9.2.0/unordered_map:45,
                 from ../BambooTracker/gui/effect_description.hpp:4,
                 from ../BambooTracker/gui/effect_description.cpp:1:
/usr/include/c++/9.2.0/bits/functional_hash.h:101:12: note: previous definition of 'struct std::hash<_Tp>'
  101 |     struct hash : __hash_enum<_Tp>
      |            ^~~~
```

**Comment by rerrahkr** [comment]
Thank you for your report.
It seems that [std::hash with enum are supported from gcc 6.1](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60970), so I fixed preprocessor directives at e1a4869237435144b5de4b3b14c713402ba38b3e.

**Comment by jpcima** [comment]
Thanks, some trouble remains on Clang compiler, which defines `__GNUC__` constant with value 4, and it will still fail.
I think adding a check for a `__clang__` definition will be appropriate.

**Comment by rerrahkr** [comment]
I fixed for clang at 74b72b101b0c1b0736867621c754af319e55b7a5.

**Comment by jpcima** [comment]
This worked on both compilers. Thanks.
